### ISSUE TITLE
Rotate at -90 or 270 fails to work.

### ISSUE THREAD

**Issue by erlicthemad** [miyako/4d-component-rotate-picture#1]
In your Rotate image, I discovered that it seems to have issues when rotating by -90 or 270 degrees. It seems that the rotate transform moves the image off of the viewport. The core works kine if I do 90 degrees and even -45 but at -45 you can see the image mostly rotated out of the view. This is my fix for the code. I'm not sure if you didn't use this due to when it was released.

`
PICTURE PROPERTIES($1;$w;$h)

// $s:=Sin($2*Degree)
// $c:=Cos($2*Degree)

// $ww:=($w*$c)+($h*$s)
// $hh:=($w*$s)+($h*$c)

$svg:=SVG_New ($ww;$hh)
$g:=SVG_New_group ($svg)
$image:=SVG_New_embedded_image ($g;$1)  // ;($ww/2)-($w/2);($hh/2)-($h/2))
  //SVG_SET_TRANSFORM_ROTATE ($g;$2;$ww/2;$hh/2)
SVG_ROTATION_CENTERED ($image;$2)
$0:=SVG_Export_to_picture ($svg)
SVG_CLEAR ($svg)
`

**Comment by miyako** [comment]
I've changed to your code.

Note: it seems SVG component commands are mostly not thread safe.

maybe it could be replaced by native DOM commands.
